theme: minima
title: Welcome To my blog
author: Lawrence Mark I
email: mlwarigia@gmail.com
phone number: +254790611333
description: I am at a place where writing has taken a spot on my wall. I hope you enjoy
